#!/usr/bin/env python3

text = '''
If you are traveling in {foreign_country} and find yourself having to cross a
piranha-filled river, here's how to do it {adverb}:
>Piranhas are more {adjective} during the day, so cross the river at night.
>Avoid areas with netted {animal} traps-piranhas my be {verb_ending_in_"ing"} there
looking to {verb} them!
>When {verb_ending_in_"ing"1} the river, swim {adverb1}.  You don't want to wake them
up and make them {adjective1}!
>Whatever you do, if you have an open wound, try to find another way to get back to
>
