#!/usr/bin/env python3

import colors as c
from utils import ask
import random

print(c.clear)
print("Welcome to the quiz game!")

print("Let's test your knowledge and see what you've learned so far!")

def q1():
    answer = ask("What color is the unicorns' fur?") 
    if answer == "pink":
        return True
    return False
    
def q2():
    answer = ask("Where are they dancing?")
    if answer.startswith("rainbow"):
        return True
    return False

def q3():
    answer = ask("Please use one word to describe the texture of their magical fur.")
    if answer.startswith("smile"):
        return True
    return False

questions = [q1,q2,q3]
while questions:
    question = random.choice(questions)
    answer = question()
    if answer:
        questions.remove(question)


