#!/usr/bin/env python3

import colors as c
import time

weeks = 0
days = 0
hours = 0
minutes = 00
seconds = 0
hundredths = 0

while True:
    time.sleep(0.01)
    print(c.clear + c.cyan + 'Ctrl+C to stop' + c.reset)
    print(str(weeks) + '-' + str(days) + '-' + str(hours) + ':' + str(minutes) + '.' + str(seconds) + '.' + str(hundredths))
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        minutes = 0
    if hours == 24:
        days += 1
        hours = 0
    if days == 7:
        weeks += 1
        days = 0
