#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.random_color() + "Do you like waffles?")
waffles = input('> ')
if waffles == 'yes':
    print(c.clear)
    print(c.random_color() + "Do you like pancakes?")
    pancakes = input('> ')
    if pancakes == 'yes':
        print(c.clear)
        print(c.random_color() + "Do you like French toast?")
        frenchtoast = input('> ')
        if frenchtoast == 'yes':
            print(c.clear)
            print(c.random_color() + "Do do do do,can't wait to get a mouthful!")
        else:
            print(c.random_color() + "Well, I like French toast...")
    else:
        print(c.random_color() + "Well, I like pancakes...")
else:
    print(c.random_color() + "Well, I like waffles...")




