#!/usr/bin/env python3

import colors as c
import random
import time

sides = []

side1 = format('''
 -------
|       |
|   o   |
|       |
 -------
''')


side2 = format('''
 -------
|o      |
|       |
|      o|
 -------
''')


side3 = format('''
 -------
|o      |
|   o   |
|      o|
 -------
''')


side4 = format('''
 -------
|o     o|
|       |
|o     o|
 -------
''')


side5 = format('''
 -------
|o     o|
|   o   |
|o     o|
 -------
''')


side6 = format('''
 -------
|o     o|
|o     o|
|o     o|
 -------
''')

sides.append(side1)
sides.append(side2)
sides.append(side3)
sides.append(side4)
sides.append(side5)
sides.append(side6)

for side in sides:
    print(c.clear)
    print(c.random_color() + side)
    time.sleep(0.5)
